<div class="jumbotron">
    <h1>Starter Application V1.0</h1>
    <p>You have successfully installed the Starter Application, a starting point for applications with complex
        business logic. It is a PHP MVC skeleton with a Domain (Domain Model), Data Mapper and Service Layer.
        It uses Zend Framework 2 however may be ported to other frameworks quite easily. You are welcome
        to use it as the foundation for your next application.
        <a href="http://staging.kimprince.com/starter/starter-application-v10" target="_blank">See here</a> for
        instructions.
    </p>
    <p><a class="btn btn-primary btn-lg" href="https://github.com/KimPrince/zf2-starter" target="_blank">
            Fork the Starter Application on github
    </a></p>
</div>